/**
 * @file game-data.js
 * @description Metadata for all 68+ games in CasinoRitmic.
 */

window.CasinoGames = {
    'card-blackjack': { key: 'reward_blackjack', icon: '🃏', name: "L'As de Beethoven", url: 'blackjack_ritmic.html' },
    'card-ruleta': { key: 'reward_ruleta', icon: '🎡', name: "La Roda de Rossini", url: 'ruleta.html' },
    'card-simon': { key: 'reward_simon', icon: '🎹', name: "La Memòria de Bach", url: 'simon.html' },
    'card-memory': { key: 'reward_memory', icon: '🧠', name: "El Cervell de Chopin", url: 'memory.html' },
    'card-texas': { key: 'reward_texas', icon: '🤠', name: "El Barret de Copland", url: 'texas.html' },
    'card-daus': { key: 'reward_daus', icon: '🎲', name: "Els Daus de Haydn", url: 'daus.html' },
    'card-bolera': { key: 'reward_bolera', icon: '🎳', name: "La Bola de Boulez", url: 'bolera.html' },
    'card-laberinto': { key: 'reward_laberinto', icon: '🧩', name: "El Fil d'Ariadna", url: 'laberinto.html' },
    'card-sudoku': { key: 'reward_sudoku', icon: '🔢', name: "La Quadrícula de Glass", url: 'sudoku.html' },
    'card-bomba': { key: 'reward_bomba', icon: '💣', name: "El Metrònom Explosiu", url: 'bomba.html' },
    'card-solitario': { key: 'reward_solitario', icon: '🃏', name: "La Paciència de Satie", url: 'solitario.html' },
    'card-cajaderitmos': { key: 'reward_cajaderitmos', icon: '🥁', name: "El Ritme de Stravinsky", url: 'cajaderitmos.html' },
    'card-tetris': { key: 'reward_tetris', icon: '🧱', name: "El Mur de Pink Floyd", url: 'tetris.html' },
    'card-roda': { key: 'reward_roda', icon: '🎡', name: "La Fortuna de Orff", url: 'rodafortuna.html' },
    'card-joker': { key: 'reward_joker', icon: '🃏', name: "El Comodí de Joplin", url: 'jokerwild.html' },
    'card-subasta': { key: 'reward_subasta', icon: '🔨', name: "El Martell de Mahler", url: 'subasta.html' },
    'card-prestamista': { key: 'reward_prestamista', icon: '💸', name: "L'Or de Verdi", url: 'prestamista.html' },
    'card-ginrumy': { key: 'reward_ginrumy', icon: '🍸', name: "La Copa de Strauss", url: 'ginrumy.html' },
    'card-pols': { key: 'reward_polsintern', icon: '💪', name: "La Força de Beethoven", url: 'polsintern.html' },
    'card-cascada': { key: 'reward_cascada', icon: '🪙', name: "La Moneda de Bizet", url: 'cascada.html' },
    'card-keno': { key: 'reward_keno', icon: '🎫', name: "El Bitllet de Gershwin", url: 'keno.html' },
    'card-dardos': { key: 'reward_dardos', icon: '🎯', name: "La Diana de Rossini", url: 'dardos.html' },
    'card-derby': { key: 'reward_derby', icon: '🏇', name: "El Cavall de Walkiria", url: 'derby.html' },
    'card-galeria': { key: 'reward_galeria', icon: '🔫', name: "El Tret de Tchaikovsky", url: 'galeriatir.html' },
    'card-cabina': { key: 'reward_cabinavent', icon: '💨', name: "El Vent de Debussy", url: 'cabinavent.html' },
    'card-escoba': { key: 'reward_escoba', icon: '🧹', name: "L'Escoba de Dukas", url: 'escoba.html' },
    'card-2048': { key: 'reward_2048', icon: '🎼', name: "La Suma de Bach", url: '2048.html' },
    'card-topos': { key: 'reward_topos', icon: '🔨', name: "El Martell de Thor", url: 'topos.html' },
    'card-paigow': { key: 'reward_paigow', icon: '🀄', name: "El Drac de Puccini", url: 'paigow.html' },
    'card-setimig': { key: 'reward_setimig', icon: '✒️', name: "La Ploma de Cervantes", url: 'setimig.html' },
    'card-scalextric': { key: 'reward_scalextric', icon: '🏎️', name: "El Motor de Adams", url: 'scalextric.html' },
    'card-klondike': { key: 'reward_klondike', icon: '🎻', name: "El Violí de Paganini", url: 'klondike.html' },
    'card-calculogic': { key: 'reward_calculogic', icon: '🔢', name: "El Nombre de Pythagoras", url: 'calculogic.html' },
    'card-vals': { key: 'reward_vals', icon: '💃', name: "El Vestit de Strauss", url: 'vals.html' },
    'card-embut': { key: 'reward_embut', icon: '⏳', name: "El Temps de Zimmer", url: 'embut.html' },
    'card-millonario': { key: 'reward_millonario', icon: '💰', name: "El Xec de Williams", url: 'millonario.html' },
    'card-conquian': { key: 'reward_conquian', icon: '🪄', name: "La Batuta de Berlioz", url: 'conquian.html' },
    'card-whist': { key: 'reward_whist', icon: '📜', name: "La Partitura d'Orfeu", url: 'whist.html' },
    'card-rutajerarquica': { key: 'reward_rutajerarquica', icon: '🗺️', name: "La Brúixola de Holst", url: 'rutajerarquica.html' },
    'card-cronometre': { key: 'reward_cronometreinvers', icon: '⏱️', name: "El Rellotge de Haydn", url: 'cronometreinvers.html' },
    'card-enceuat': { key: 'reward_enceuat', icon: '📝', name: "La Ploma de Shakespeare", url: 'enceuat.html' },
    'card-algebra': { key: 'reward_algebra', icon: '➕', name: "L'Àbac de Xenakis", url: 'algebraritmica.html' },
    'card-escalada': { key: 'reward_escalada', icon: '🧗', name: "La Corda de Strauss", url: 'escalada.html' },
    'card-highstriker': { key: 'reward_highstriker', icon: '🔨', name: "El Martell de Wagner", url: 'highstriker.html' },
    'card-piscina': { key: 'reward_piscina', icon: '🌊', name: "La Partitura de Debussy", url: 'tirapiscina.html' },
    'card-scrabble': { key: 'reward_scrabble', icon: '📜', name: "La Lletra de Schubert", url: 'scrabble.html' },
    'card-cronodirecte': { key: 'reward_cronometre', icon: '⏱️', name: "El Pèndol de Maelzel", url: 'cronometre.html' },
    'card-speed': { key: 'reward_speed', icon: '⚡', name: "El Llampec de Liszt", url: 'speed.html' },
};
